bot:
  automerge: true
  inspection: update-grayskull
conda_forge_output_validation: true
provider: {linux_aarch64: emulated, linux_ppc64le: emulated, win: azure}
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
